name: CI/CD Pipeline

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04.01

    steps:
    - name: Build Docker image
      run: |
        docker build -t my-nuxt-app .
        
    - name: Push Docker image to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker tag my-nuxt-app:latest ${{ secrets.DOCKER_USERNAME }}/my-nuxt-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-nuxt-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-22.04.01

    steps:
    - name: Deploy to remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-nuxt-app:latest
          docker stop my-nuxt-app || true
          docker rm my-nuxt-app || true
          docker rmi ${{ secrets.DOCKER_USERNAME }}/my-nuxt-app:current || true
          docker tag ${{ secrets.DOCKER_USERNAME }}/my-nuxt-app:latest ${{ secrets.DOCKER_USERNAME }}/my-nuxt-app:current
          docker run -d --name my-nuxt-app -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/my-nuxt-app:current
