name: CI/CD Pipeline

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t profori .
        
    - name: Push Docker image to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker tag profori:latest ${{ secrets.DOCKER_USERNAME }}/profori:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/profori:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-nuxt-app:latest
          docker stop profori || true
          docker rm profori || true
          docker rmi ${{ secrets.DOCKER_USERNAME }}/profori:current || true
          docker tag ${{ secrets.DOCKER_USERNAME }}/profori:latest ${{ secrets.DOCKER_USERNAME }}/profori:current
          docker run -d --name profori -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/profori:current
  

